<?php

namespace Crm\ProductoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LineaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LineaRepository extends EntityRepository
{
}
